### ISSUE TITLE
1.8 loading error

### ISSUE THREAD

**Issue by Chopnex** [pqtriick/LabySK#1]
Hello! So cool to see you're making this addon for skript. 

I tried to use the 1.8.8 version and received this error when restarting the server.

https://pastebin.com/10WTwCEN

Maybe you can fix this. Tell me if you need any more information :))

**Comment by pqtriick** [comment]
Hey! Thanks for using the Addon. This addon was in first place only for the version 1.20.4 . I already had Problems on the 1.8. I will try to fix it but I would recommend you the 1.20 version.

**Comment by Chopnex** [comment]
Cool! Would be so great if it was possible for you to fix since my server is 1.8. You mean that the 1.20 version should work with 1.8 aswell?

**Comment by pqtriick** [comment]
No it won't because the spigot api in the plugin is for 1.20.4. But i will try to build a version for 1.8

**Comment by Chopnex** [comment]
Ahh makes sense, would be appreciated very much if you could make the 1.8 work :))

**Comment by pqtriick** [comment]
Hey!
I managed to run it on Version 1.8
You can download the 1.8 File from here: https://github.com/pqtriick/LabySK/releases/tag/mcv_1.8.8
Hopefully this helps. I would really appreciate it if you could rate the plugin on SpigotMC! :)
https://imgur.com/a/3lyVMbZ
